export const areas = [
  {
    slug: "gwadar",
    nameKey: "areaGwadar",
    regionKey: "regionBalochistan",
    descKey: "areaGwadarDesc",
    tagKey: "exploreGwadar",
    lat: 25.1264,
    lng: 62.3225,
    image: "/images/gwadar.jpg",
  },
  {
    slug: "pasni",
    nameKey: "areaPasni",
    regionKey: "regionMakran",
    descKey: "areaPasniDesc",
    tagKey: "explorePasni",
    lat: 25.2631,
    lng: 63.471,
    image: "/images/pasni.jpg",
  },
  {
    slug: "ormara",
    nameKey: "areaOrmara",
    regionKey: "regionMakran",
    descKey: "areaOrmaraDesc",
    tagKey: "exploreOrmara",
    lat: 25.2088,
    lng: 64.6357,
    image: "/images/ormara.jpg",
  },
  {
    slug: "jiwani",
    nameKey: "areaJiwani",
    regionKey: "regionWestern",
    descKey: "areaJiwaniDesc",
    tagKey: "exploreJiwani",
    lat: 25.0488,
    lng: 61.7458,
    image: "/images/jiwani.jpg",
  },
];

export const fish = [
  {
    id: 1,
    nameKey: "fishKing",
    sci: "Scomberomorus cavalla",
    catKey: "catPelagic",
    descKey: "fishKingDesc",
    image: "/images/king-mackerel.jpg",
  },
  {
    id: 2,
    nameKey: "fishIndian",
    sci: "Rastrelliger kanagurta",
    catKey: "catPelagic",
    descKey: "fishIndianDesc",
    image: "/images/indian-mackerel.jpg",
  },
  {
    id: 3,
    nameKey: "fishBarra",
    sci: "Sphyraena barracuda",
    catKey: "catPelagic",
    descKey: "fishBarraDesc",
    image: "/images/barracuda.jpg",
  },
  {
    id: 4,
    nameKey: "fishGrouper",
    sci: "Epinephelus spp.",
    catKey: "catReef",
    descKey: "fishGrouperDesc",
    image: "/images/grouper.jpg",
  },
  {
    id: 5,
    nameKey: "fishPomfret",
    sci: "Pampus spp.",
    catKey: "catDemersal",
    descKey: "fishPomfretDesc",
    image: "/images/pomfret.jpg",
  },
  {
    id: 6,
    nameKey: "fishTuna",
    sci: "Thunnus spp.",
    catKey: "catPelagic",
    descKey: "fishTunaDesc",
    image: "/images/tuna.jpg",
  },
];

export const coastalLocations = [
  {
    id: "gwadar",
    nameKey: "areaGwadar",
    type: "area",
    catKey: "catMajorCoast",
    lat: 25.1264,
    lng: 62.3225,
    descKey: "locGwadar",
  },
  {
    id: "pasni",
    nameKey: "areaPasni",
    type: "area",
    catKey: "catFishingTown",
    lat: 25.2631,
    lng: 63.471,
    descKey: "locPasni",
  },
  {
    id: "ormara",
    nameKey: "areaOrmara",
    type: "area",
    catKey: "catCoastalArea",
    lat: 25.2088,
    lng: 64.6357,
    descKey: "locOrmara",
  },
  {
    id: "jiwani",
    nameKey: "areaJiwani",
    type: "area",
    catKey: "catFishingCoast",
    lat: 25.0488,
    lng: 61.7458,
    descKey: "locJiwani",
  },
  {
    id: "pishukan",
    nameKey: "locPishukanName",
    type: "fishing",
    catKey: "catFishingArea",
    lat: 25.245,
    lng: 62.045,
    descKey: "locPishukan",
  },
  {
    id: "sur",
    nameKey: "locSurName",
    type: "fishing",
    catKey: "catFishingArea",
    lat: 25.27,
    lng: 62.18,
    descKey: "locSur",
  },
  {
    id: "gwadar-harbour",
    nameKey: "locGwadarHName",
    type: "fishing",
    catKey: "catHarbour",
    lat: 25.116,
    lng: 62.335,
    descKey: "locGwadarH",
  },
  {
    id: "pasni-harbour",
    nameKey: "locPasniHName",
    type: "fishing",
    catKey: "catHarbour",
    lat: 25.261,
    lng: 63.476,
    descKey: "locPasniH",
  },
  {
    id: "jiwani-harbour",
    nameKey: "locJiwaniHName",
    type: "fishing",
    catKey: "catFishingArea",
    lat: 25.055,
    lng: 61.752,
    descKey: "locJiwaniH",
  },
  {
    id: "gwadar-beach",
    nameKey: "locGwadarBName",
    type: "beach",
    catKey: "catBeach",
    lat: 25.105,
    lng: 62.34,
    descKey: "locGwadarB",
  },
  {
    id: "ormara-beach",
    nameKey: "locOrmaraBName",
    type: "beach",
    catKey: "catBeach",
    lat: 25.205,
    lng: 64.65,
    descKey: "locOrmaraB",
  },
  {
    id: "jiwani-beach",
    nameKey: "locJiwaniBName",
    type: "beach",
    catKey: "catBeach",
    lat: 25.05,
    lng: 61.735,
    descKey: "locJiwaniB",
  },
];
